# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Geekend Update
email: tylerwchilds@gmail.com
description: > Geekend Update is a merry old band of fellows
  discussing geek pop culture, including, but not limited to,
  comics, television, movies, and gaming. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "//geekendpodcast.com" # the base hostname & protocol for your site
twitter_username: tylerchilds
github_username:  tylerchilds

# Build settings
markdown: kramdown
